DogMode.Admin/DogMode.Admin/Controllers/DogOwnerController.cs
using DogMode.BusinessAccess.Extensions;
using DogMode.BusinessAccess.Repositories;
using DogMode.Context;
using DogMode.Models;
using Newtonsoft.Json;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace DogMode.Admin.Controllers
{

    [Authorize]
    public class DogOwnerController : BaseController<DogOwnerRepository,DogOwner>
    {
        // GET: DogOwner
        public ActionResult Index()
        {
            return View();
        }

        // GET: DogOwner/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var model = await Repository.FindByIdAsync(id, "Dogs", "Dogs.DogBreed");

            ViewBag.Dogs = model.Dogs.ToList();

            return View(model);
        }



        // GET: DogOwner/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            
            return View(id.HasValue ? (await Repository.FindByIdAsync(id.Value)) : new DogOwner());
        }

        // POST: DogOwner/Edit/5
        [HttpPost]
        public async Task< ActionResult> Edit( DogOwner model)
        {
            if(ModelState.IsValid)
            {
                // TODO: Add update logic here
                Repository.InsertOrUpdate(model);

                await Repository.SaveAsync();

                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpPost]
        /// <summary>
        /// Ajax Async Search Grid.
        /// </summary>
        /// <param name="filter"></param>
        /// <returns></returns>
        public ActionResult SearchAsync(FilterOptionModel filter)
        {
             
            var model = Repository.GetSummary(filter);
            ViewBag.FilterModel = filter.Serialize();

            return View("Partials/ManageGrid", model.ToPagedList(filter.page == 0 ? 1 : filter.page, filter.Limit));
        }


        public ActionResult Search(string filterdata, int? page, string columnName, string sortOrder)
        {
            var filter = JsonConvert.DeserializeObject<FilterOptionModel>(filterdata);
            var model = Repository.GetSummary(filter);

            filter.page = page != null ? (int)page : 1;

            ViewBag.FilterModel = JsonConvert.SerializeObject(filter);
            ViewBag.Filter = filter;

            if (!string.IsNullOrEmpty(columnName) && !string.IsNullOrEmpty(sortOrder))
            {
                ViewBag.CurrentColumnSort = columnName;
                ViewBag.SortOrder = sortOrder;
                return View("Partials/ManageGrid", model.OrderBy(columnName, sortOrder).ToPagedList(page ?? 1, filter.Limit));
            }

            return View("Partials/ManageGrid", model.ToPagedList(page ?? 1, filter.Limit));
        }

        [HttpPost]
        public ActionResult Sort(string filter, string columnName, string sortOrder, string currentColumn, int? page)
        {
            var _filter = JsonConvert.DeserializeObject<FilterOptionModel>(filter);
            var model = Repository.GetSummary(_filter);

            sortOrder = string.IsNullOrEmpty(sortOrder) ? "ASC" : sortOrder == "ASC" ? "DESC" : "ASC";

            if (currentColumn != null)
                sortOrder = columnName != currentColumn ? "ASC" : sortOrder;

            ViewBag.CurrentColumnSort = columnName;
            ViewBag.SortOrder = sortOrder;
            ViewBag.FilterModel = filter;

            return View("Partials/ManageGrid", model.OrderBy(columnName, sortOrder).ToPagedList(_filter.page, _filter.Limit));
        }




        public ActionResult Statuses()
        {
            var model = Enum.GetValues(typeof(DogStatus)).Cast<DogStatus>()
             .Select(i => new
             {
                 Id = (int)i,
                 Name = i.ToString(),
             }).ToList();

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> UpdateStatus(int id, DogStatus status)
        {
            // ViewBag.ActionMessage = Repository.MessageForStatus(status);
            var model = await Repository.FindByIdAsync(id, "User", "Category");
           // model.Status = status;
            await Repository.SaveAsync();
            //return View("Partials/ConfirmAction", model);
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]

        public async Task<ActionResult> sendpush(int id)
        {
            var model = await Repository.FindByIdAsync(id);

            //await NotificationsManager.SendNotificationAsync(model.Title, author, model.Id, model.CategoryId);

            return Json(true, JsonRequestBehavior.AllowGet);
        }


        public async Task<ActionResult> Delete(int id)
        {
            var model = await Repository.FindByIdAsync(id);

            return View(model);
        }
        [HttpPost]
        public async Task<ActionResult> Delete(int id, FormCollection collection)
        {
            DogOwner model = null;
            using (var context = ApplicationContext.Create())
            {
                var repo = new DogOwnerRepository() { Context = context };
                model = await repo.FindByIdAsync(id);
            }

            try
            {

            await Repository.DeleteByIdAsync(id);

            return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                // TODO log this
                ViewBag.Error = "Cannot delete; must delete associated dog(s) first.";
                return View(model);
            }
        }
    }
}

DogMode.Admin/DogMode.Admin/Controllers/FeedsController.cs
using DogMode.BusinessAccess.Extensions;
using DogMode.BusinessAccess.Repositories;
using DogMode.Models;
using Newtonsoft.Json;
using PagedList;
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace DogMode.Admin.Controllers
{
    //[Globalization]
    public class FeedsController : BaseController<FeedsRepository, Dog>
    {
        // GET: Feeds       
        [Authorize(Roles = "Admin,Publisher")]
        public ActionResult Index()
        {
           
            return View();
        }
        #region Grid admin  Feeds
   

        public async Task<ActionResult> Edit(int? id)
        {
            var model = id.HasValue ? (await Repository.FindByIdAsync(id.Value, "Campaing","Beacon")) : new Dog();

            
            return View(model);
        }

        
        [HttpPost]
        public async Task<ActionResult> Edit(Dog model)
        {
            if (ModelState.IsValid)
            {
                // Insert Or Update existing.
                Repository.InsertOrUpdate(model);
                

                await Repository.SaveAsync();

                return RedirectToAction("Index");
            }
            //ViewBag.Categories = (await Repository.GetCategoriesAsync()).ToSelectList(m => m.Name, m => m.Id.ToString(), "Select Category");

            return View(model);
        }

        public async Task<ActionResult> Details(int id)
        {
            var model = await Repository.FindByIdAsync(id, "Category", "User");


            return View("Partials/Details", model);
        }



        /// <summary>
        /// Ajax Async Search Grid.
        /// </summary>
        /// <param name="filter"></param>
        /// <returns></returns>
        public ActionResult SearchAync(FilterOptionModel filter)
        {
            filter.companyId = ClaimsPrincipal.Current.CenterId();
            var model = Repository.GetSummary(filter);
            ViewBag.FilterModel = filter.Serialize();

            return View("Partials/ManageGrid", model.ToPagedList(filter.page == 0 ? 1 : filter.page, filter.Limit));
        }


        public ActionResult SearchFeeds(string filterdata, int? page, string columnName, string sortOrder)
        {
            var filter = JsonConvert.DeserializeObject<FilterOptionModel>(filterdata);
            var model = Repository.GetSummary(filter);

            filter.page = page != null ? (int)page : 1;

            ViewBag.FilterModel = JsonConvert.SerializeObject(filter);
            ViewBag.Filter = filter;

            if (!string.IsNullOrEmpty(columnName) && !string.IsNullOrEmpty(sortOrder))
            {
                ViewBag.CurrentColumnSort = columnName;
                ViewBag.SortOrder = sortOrder;
                return View("Partials/ManageGrid", model.OrderBy(columnName, sortOrder).ToPagedList(page ?? 1, filter.Limit));
            }

            return View("Partials/ManageGrid", model.ToPagedList(page ?? 1, filter.Limit));
        }

        [HttpPost]
        public ActionResult Sort(string filter, string columnName, string sortOrder, string currentColumn, int? page)
        {
            var _filter = JsonConvert.DeserializeObject<FilterOptionModel>(filter);
            var model = Repository.GetSummary(_filter);

            sortOrder = string.IsNullOrEmpty(sortOrder) ? "ASC" : sortOrder == "ASC" ? "DESC" : "ASC";

            if (currentColumn != null)
                sortOrder = columnName != currentColumn ? "ASC" : sortOrder;

            ViewBag.CurrentColumnSort = columnName;
            ViewBag.SortOrder = sortOrder;
            ViewBag.FilterModel = filter;

            return View("Partials/ManageGrid", model.OrderBy(columnName, sortOrder).ToPagedList(_filter.page, _filter.Limit));
        }




        public ActionResult Statuses()
        {
            var model = Enum.GetValues(typeof(DogStatus)).Cast<DogStatus>()
             .Select(i => new
             {
                 Id = (int)i,
                 Name = i.ToString(),
             }).ToList();

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> UpdateStatus(int id, DogStatus status)
        {
            // ViewBag.ActionMessage = Repository.MessageForStatus(status);
            var model = await Repository.FindByIdAsync(id, "User", "Category");
            model.Status = status;
            await Repository.SaveAsync();
            //return View("Partials/ConfirmAction", model);
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]

        public async Task<ActionResult> sendpush(int id)
        {
            var model = await Repository.FindByIdAsync(id, "Category");
             
            //await NotificationsManager.SendNotificationAsync(model.Title, author, model.Id, model.CategoryId);

            return Json(true, JsonRequestBehavior.AllowGet);
        }
        

        public async Task<ActionResult> Delete(int id)
        {
            var model = await Repository.FindByIdAsync(id);

            return View(model);
        }
        [HttpPost]
        public async Task<ActionResult> Delete(int id, FormCollection collection)
        {

            await Repository.DeleteByIdAsync(id);

            return RedirectToAction("Index");
        }

        #endregion   Grid  admin feed  
    }
}

DogMode.Admin/DogMode.Admin/Views/DogOwner/Delete.cshtml
@model DogMode.Models.DogOwner

@{
    ViewBag.Title = "Delete";
    var errormessage = !string.IsNullOrEmpty(ViewBag.Error) ? (string)ViewBag.Error : string.Empty;
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Delete</h2>
        <ol class="breadcrumb">
            <li>
                @Html.ActionLink("List", "Index")
            </li>
            <li class="active">
                <strong>Delete</strong>
            </li>
        </ol>
    </div>
    <div class="col-sm-8">
        <div class="title-action">
			@Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary"})
        </div>
    </div>
</div>


<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>DogOwner</h5>
                </div>
                <div class="ibox-content">

				<h4 class="text-danger">Are you sure you want to delete this?</h4>
                    <h5 class="text-danger">@errormessage</h5>
				 <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-primary" />
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-white"})
        </div>
    }



                </div>
            </div>
        </div>
    </div>
 </div>

DogMode.Admin/DogMode.Admin/Views/DogOwner/Details.cshtml
@model DogMode.Models.DogOwner

@{
    ViewBag.Title = "Details";
    Layout = null;


}
@Html.Partial("typeahead")
<!-- Large modal -->
<div id="createNewDogSection">

    @Html.Partial("Partials/CreateNewDog", new Dog())
</div>
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Details</h2>
        <ol class="breadcrumb">
            <li>
                @Html.ActionLink("List", "Index")
            </li>
            <li class="active">
                <strong>Details</strong>
            </li>
        </ol>
    </div>
</div>


<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Details Dog Owner</h5>
                </div>
                <div class="ibox-content">

                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.CreatedDate)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.CreatedDate)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.Name)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Name)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.LastName)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.LastName)
                        </dd>
                    </dl>

                    <div class="row">
                        @Html.Partial("Partials/DogList", (IEnumerable<Dog>)ViewBag.Dogs)
                    </div>
                    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary" })
                    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-white" })
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts
{

    @Scripts.Render("~/plugins/dropZone")
    <script type="text/javascript">
        $(document).ready(function () {
            $(".thumb").each(function () {
                if (typeof $(this).prop("src") == "undefined" || $(this).prop("src") == "") {
                    $(this).attr("src", 'https://dogmode.blob.core.windows.net/images/animal-paw-print.png');
                }
            })
        })
    </script>
}

@section Styles {
    @Styles.Render("~/Content/plugins/dropzone/dropZoneStyles")
}

DogMode.Admin/DogMode.Admin/Views/DogOwner/Edit.cshtml
@model DogMode.Models.DogOwner

@{
    var PageLabel = "Edit";
    ViewBag.Title =PageLabel= Model?.Id==0? "Add":"Edit";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>@PageLabel</h2>
        <ol class="breadcrumb">
            <li>
                @Html.ActionLink("List", "Index")
            </li>
            <li class="active">
                <strong>@PageLabel</strong>
            </li>
        </ol>
    </div>
    <div class="col-sm-8">
        <div class="title-action">
			@Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary"})
        </div>
    </div>
</div>



<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>@string.Format("{0} Dog Owner",PageLabel) </h5>
                </div>
                <div class="ibox-content">

				@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedDate)
                @Html.ValidationMessageFor(model => model.CreatedDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName)
                @Html.ValidationMessageFor(model => model.LastName)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
				@Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-white"})
            </div>
        </div>
    </div>
}


                </div>
            </div>
        </div>
    </div>
 </div>

DogMode.Admin/DogMode.Admin/Views/DogOwner/Index.cshtml
@{
    ViewBag.Title = "Dog Owners";
}


@{
    ViewBag.Title = "Dog Owners";

    if (Request.IsAjaxRequest())
    {
        Layout = null;
    }
    var options = new AjaxOptions()
    {
        HttpMethod = "post",
        InsertionMode = InsertionMode.Replace,
        LoadingElementId = "loader",
        UpdateTargetId = "BookingListSection"
    };

    var name = Model != null ? Model.Name : AppConstants.ApplicationAdministratorTitle;
}
@model  Company

@Html.Partial("typeahead")

@Scripts.Render("~/plugins/knockout")
@Scripts.Render("~/plugins/slick")
@Styles.Render("~/plugins/slickStyles")
@Styles.Render("~/plugins/slickThemeStyles")



<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>DOG OWNERS</h2>
        <ol class="breadcrumb">
            <li>
                @Html.ActionLink("Admin ", "Index", "DogOwner")
            </li>
            <li class="active">
                <strong>Dog Owners</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="wrapper wrapper-content  animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Search Dog Owners</h5>
                    <div class="ibox-tools">
                        @Html.ActionLink(" ", "Edit", "DogOwner", null, new { @class = "btn btn-danger btn-circle btn-outline fa fa-plus" })
                    </div>
                </div>
                <div class="ibox-content text-center">
                    @Html.Partial("Partials/Filters", new FilterOptionModel() { companyId = Model != null ? Model.Id : (int?)null })
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-lg-12" id="BookingListSection"></div>
        </div>

    </div>


    <script type="text/javascript">


    var pagelimit = 0;

    var viewmodel = {
        roles: [],
        statuses: [],
        keywords: ko.observable(),
        seelctedStatus: ko.observable(),


        onSelectionChange: function () {
            $("#page").val('0');
            doSearch();
        },
        onSelectionStatusChange: function () {
            $("#page").val('0');
            doSearch();
        },

        cleanFilters: function () {

            $("#page").val('0');
            $("#keywords").val('');
            $("#FeedStatus").val(-1);
            doSearch();
        }

    };
    // Initialize

    function doSearch() {
        $("#searchbookingsform").submit();
    }

    $(function () {


        @*$.get('@Url.Action("Statuses", "Feeds")', function (status) {
            viewmodel.statuses = status;
            applybindigs(status);
        });*@

        $("#searchbookingsform").submit();


    });
    function applybindigs(statuses) {

        console.log("Try apply bindings");
        viewmodel.statuses = statuses;
        ko.applyBindings(viewmodel);

    };

    function showDetails() {
        viewmodel.MainshowDetails();
    }


    function showmodal() {
        $("#bookingModal").html(null);

        $('#ChangeState').modal('show');
    }
    function hideModal() {
        $('#ChangeState').hide();
    }


    function GetBookingUpdateView(url) {
        $.ajax({
            type: "POST",
            url: url,
            //data: ,
            datatype: "html",
            success: function (data) {
                $('#bookingModal').html(data);

            }
        });
    }
    function UpdateStatus(id,status) {
        console.log("FEED uid :" + id);

        swal({
            title: "Do you want Update Status?",
            text: "To "+ status +"! ",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#008000",
            confirmButtonText: "Yes",
            cancelButtonText: "No",
            closeOnConfirm: false,
            closeOnCancel: false
        },
                       function (isConfirm) {
                           if (isConfirm) {
                               $("#loaderSection").fadeIn();
                               $.post('@Url.Action("updatestatus","feeds")' + "?id=" + id+"&status="+status, function (data) {
                                   $.post('@Url.Action("Details","Feeds")' + "?id=" + id, function (view) {
                                       $("#BookingListSection").html(view);
                                       $("#loaderSection").fadeOut();
                                   });
                               });
                               swal("Changed!", "status has been changed to "+status, "success");
                           } else {

                              swal("Cancelled", "canceled", "error");
                           }
                       });
    }

    function ShowUserDetails(userid) {
        console.log("user id: " + userid);
        showmodal();
        GetBookingUpdateView('@Url.Action("UserSummary", "Feeds")' + "?id=" + userid);
    }

    function OnCompleteBookingUpdate(result) {
        console.log("nuevo resultado ");
        console.log(result);
        $("#searchbookingsform").submit();
        hideModal();
    }

    function sendPushNotification(id) {
         swal({
                    title: "Send Push Notificatons?",
                    text: "Do you want to send for  all devices!",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#008000",
                    confirmButtonText: "Yes, send it!",
                    cancelButtonText: "No, cancel!",
                    closeOnConfirm: false,
                    closeOnCancel: false
                },
                        function (isConfirm) {
                            if (isConfirm) {
                                $.post('@Url.Action("sendpush","feeds")'+"?id="+id, function (data) {
                                    console.log("ok push");
                                });
                                swal("Requested!", "Notification Has been send", "success");
                            } else {
                                swal("Cancelled", "Notification canceled", "error");
                            }
                        });
    }

    $(function () {



        //$('#CompanyName').on('typeahead:selected', function (e, datum) {
        //    console.log('companyID: ' + datum.id);
        //    // set value manually
        //    $("#CompanyToFilterId").val(datum.id);
        //    $("#searchbookingsform").submit();

        //});
        //$('#CampaignName').on('typeahead:selected', function (e, datum) {
        //    console.log('CampaignId: ' + datum.id);
        //    // set value manually
        //    $("#CampaignId").val(datum.id);
        //    $("#searchbookingsform").submit();

        //});
        //$('#CategoryName').on('typeahead:selected', function (e, datum) {
        //    console.log('CampaignId: ' + datum.id);
        //    // set value manually
        //    $("#BeaconId").val(datum.id);
        //    $("#searchbookingsform").submit();

        //});

    });

    </script>


    @Styles.Render("~/plugins/sweetAlertStyles")
    @Scripts.Render("~/plugins/sweetAlert")