DogMode.Admin/DogMode.Admin/Controllers/AppointmentsController.cs
using DogMode.Admin.Hub;
using DogMode.BusinessAccess.Extensions;
using DogMode.BusinessAccess.Repositories;
using DogMode.Context;
using DogMode.Models;
using Microsoft.AspNet.SignalR;
using Newtonsoft.Json;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace DogMode.Admin.Controllers
{

    [Globalization]
    public class AppointmentsController : BaseController<AppointmentsRepository, Appointment>
    {
        // GET: DogOwner
        public ActionResult Index()
        {
            return View();
        }

        // GET: DogOwner/Details/5
        public async Task<ActionResult> Details(int id)
        {
            return View(await Repository.GetDetailedAppointmentAsync(id));
        }



        // GET: DogOwner/Edit/5
        public async Task<ActionResult> Add(int? id)
        {
            
           return id.HasValue? View(await Repository.GetAppointmentViewModelFromDogId(id.Value)):  View();
        }

        public async Task<ActionResult> EditAppointment(int id)
        {
            return View(await Repository.FindByIdAsync(id));
        }

        public async Task<ActionResult> Edit(int id)
        {
            return View(await Repository.FindByIdAsync(id,"Dog","Dog.DogBreed"));
        }

        // POST: DogOwner/Edit/5
        [HttpPost]
        public async Task<ActionResult> Edit(Appointment model)
        {
            if (ModelState.IsValid)
            {
                decimal paidHours = await Repository.GetPaidHoursAsync(model.Id) ;

                if (model.PaidHours  != paidHours) model.CheckOut = model.CheckIn.AddHours((double) model.PaidHours);

                // TODO: Add update logic here
                Repository.InsertOrUpdate(model);

                await Repository.SaveAsync();

                FireSyncAction(null);

                return RedirectToAction("Index");
            }

            model.Dog = await Repository.FindDogAsync(model.DogId);

            return View(model);
        }

         
        [HttpGet]
        public async Task<JsonResult> GetDogsForOwner(int ownerId)
        {
            return Json(await Repository.GetDogsAppointmentViewModelAsync(ownerId), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<JsonResult> CreateAppointments(List<DogAppointmentViewModel> appointments)
        {

            var result = await Repository.CreateAppointments(appointments);

            if (result.success) FireSyncAction(null);

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<JsonResult> UpdateStatus(int id,QueueStatus status )
        {
            var result = await Repository.UpdateStatusAsync(id, status);

            var syncModel = await Repository.FindAppointmentViewModel(id);

            FireSyncAction(syncModel);

            return Json(result, JsonRequestBehavior.AllowGet);
        }


        [HttpGet] 
        public ActionResult CreateNewDog()
        {
            return View("Partials/CreateNewDog", new Dog());
        }

        [HttpPost]
        public async Task< JsonResult >CreateNewDog(Dog model)
        {
            if (ModelState.IsValid || (model.DogOwnerId!=0 && model.DogBreedId!=0))
            {
                var result = await Repository.CreateNewDogAsync(model);

                var ownerName =await Repository.GetOwnerNameAsync(model.DogOwnerId);

                var json = new
                {
                    OwnerId = model.DogOwnerId,
                    DogId = model.Id,
                    status = result.success ? "ok" : "error",
                    OwnerName = ownerName,
                    message = result.message
                };

                return Json(json,JsonRequestBehavior.AllowGet);
            }
            return Json(new { OwnerId = model.DogOwnerId, DogId = model.Id, status = "error" }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        /// <summary>
        /// Ajax Async Search Grid.
        /// </summary>
        /// <param name="filter"></param>
        /// <returns></returns>
        public ActionResult SearchAsync(FilterOptionModel filter)
        {

            var model = Repository.GetSummary(filter);
            ViewBag.FilterModel = filter.Serialize();

            return View("Partials/ManageGrid", model.ToPagedList(filter.page == 0 ? 1 : filter.page, filter.Limit));
        }


        public ActionResult Search(string filterdata, int? page, string columnName, string sortOrder)
        {
            var filter = JsonConvert.DeserializeObject<FilterOptionModel>(filterdata);
            var model = Repository.GetSummary(filter);

            filter.page = page != null ? (int)page : 1;

            ViewBag.FilterModel = JsonConvert.SerializeObject(filter);
            ViewBag.Filter = filter;

            if (!string.IsNullOrEmpty(columnName) && !string.IsNullOrEmpty(sortOrder))
            {
                ViewBag.CurrentColumnSort = columnName;
                ViewBag.SortOrder = sortOrder;
                return View("Partials/ManageGrid", model.OrderBy(columnName, sortOrder).ToPagedList(page ?? 1, filter.Limit));
            }

            return View("Partials/ManageGrid", model.ToPagedList(page ?? 1, filter.Limit));
        }

        [HttpPost]
        public ActionResult Sort(string filter, string columnName, string sortOrder, string currentColumn, int? page)
        {
            var _filter = JsonConvert.DeserializeObject<FilterOptionModel>(filter);
            var model = Repository.GetSummary(_filter);

            sortOrder = string.IsNullOrEmpty(sortOrder) ? "ASC" : sortOrder == "ASC" ? "DESC" : "ASC";

            if (currentColumn != null)
                sortOrder = columnName != currentColumn ? "ASC" : sortOrder;

            ViewBag.CurrentColumnSort = columnName;
            ViewBag.SortOrder = sortOrder;
            ViewBag.FilterModel = filter;

            return View("Partials/ManageGrid", model.OrderBy(columnName, sortOrder).ToPagedList(_filter.page, _filter.Limit));
        }




        public ActionResult Gettypes()
        {
            return Json(CollectionExtensions.AsEnumList<AppointmentType>(), JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetTypesByDescending()
        {
            return Json(CollectionExtensions.AsEnumList<AppointmentType>().OrderByDescending(t => t.Id).ToList(), JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetStatuses()
        {
            return Json(CollectionExtensions.AsEnumList<QueueStatus>(), JsonRequestBehavior.AllowGet);
        }

         

        public async Task<ActionResult> UpdateStatus(int id, DogStatus status)
        {
            // ViewBag.ActionMessage = Repository.MessageForStatus(status);
            var model = await Repository.FindByIdAsync(id, "User", "Category");
            // model.Status = status;
            await Repository.SaveAsync();
            //return View("Partials/ConfirmAction", model);
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]

        public async Task<ActionResult> sendpush(int id)
        {
            var model = await Repository.FindByIdAsync(id);

            //await NotificationsManager.SendNotificationAsync(model.Title, author, model.Id, model.CategoryId);

            return Json(true, JsonRequestBehavior.AllowGet);
        }


        public async Task<ActionResult> Delete(int id)
        {
            var model = await Repository.GetDetailedAppointmentAsync(id);

            return View(model);
        }
        [HttpPost]
        public async Task<ActionResult> Delete(int id, FormCollection collection)
        {

            await Repository.DeleteByIdAsync(id);

            FireSyncAction(null);

            return RedirectToAction("Index");
        }

        private void FireSyncAction(AppointmentViewModel model)
        {
             HubContext.Clients.All.Sync(model);
        }
        //context.Clients.All.FireSync(model);

        private IHubContext HubContext
        {
            get
            {
                return GlobalHost.ConnectionManager.GetHubContext<NotifyHub>();
                
            }
        }
    }
}

DogMode.Admin/DogMode.Admin/Controllers/FileUploadController.cs
using Extensions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace DogMode.Admin.Controllers
{
    public class FileUploadController : Controller
    {
        public async Task<ActionResult> Upload()
        {
            bool isSavedSuccessfully = false;

            string fName = "";

            foreach (string fileName in Request.Files)
            {
                HttpPostedFileBase file = Request.Files[fileName];
                //Save file content goes here

                if (file != null && file.ContentLength > 0)
                {

                    var name = $"FeedImages/{AzureHelper.RandomFileName(5, file.FileName)}";
                    isSavedSuccessfully = await AzureHelper.UploadAsync(name, file.CropImage());

                    fName = AzureHelper.GetAzureImageFormat(name);


                }

            }

            if (isSavedSuccessfully)
            {
                return Json(new { Message = fName });
            }
            else
            {
                return Json(new { Message = "Error in saving file" });
            }

        }
    }
}

DogMode.Admin/DogMode.Admin/Views/Shared/Partials/CreateNewDog.cshtml
 @model  Dog
     @{ 
         Layout = null;
         var options = new AjaxOptions()
         {
             HttpMethod ="post",
             OnBegin="Loading",
             OnSuccess="OnDogCreated",
             OnFailure="SomethingwentWrong"
         };
     }

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="exampleModalLabel">Add New Dog</h4>
            </div>
            <div class="modal-body">

                <div class="row">
                    <div class="col-md-8">

                        <form id="uploader" class="dropzone" action="@Url.Action("Upload", "FileUpload")" method="post"
                              enctype="multipart/form-data">
                            <div class="dropzone-previews"></div>
                            <button id="submituploadbutton" type="submit" class="btn btn-primary pull-right" disabled  >Save Picture!</button>
                        </form>
                    </div>
                    <div class="col-md-4">
                        
                        <div class="row">

                            <img id="thumb" class="img-thumbnail" style="max-height: 175px" />
                        </div>
                    </div>
                </div>
                <div class="row">
                    @using (Ajax.BeginForm("CreateNewDog","Appointments",options))
{
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            @Html.ValidationSummary(true)
            @Html.HiddenFor(model => model.Id)

            @Html.HiddenFor(model=> model.CreatedDate)
            @Html.HiddenFor(model=> model.Icon)
            @Html.HiddenFor(model=> model.Image)
            @Html.HiddenFor(model=> model.LastUpdate)


            <div class="form-group">
                @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name)
                    @Html.ValidationMessageFor(model => model.Name)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LastName, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastName)
                    @Html.ValidationMessageFor(model => model.LastName)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DogBreedId, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.AutocompleteFor(model => model.DogBreeadForSearch, model => model.DogBreedId, "GetBreeds", "TypeAhead", false, new { htmlAttributes = new { placeholder = "Search Dog Breed" } })
                    @Html.HiddenFor(model => model.DogBreedId)
                    @Html.ValidationMessageFor(model => model.DogBreedId)
                </div>
            </div>
            <div class="form-group">
                <ul class="nav" role="tablist">
                    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">With Existing Owner?</a></li>
                    <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Name to Add New Owner</a></li>

                </ul>
            </div>

            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="home">
                    <div class="form-group">
                        @Html.LabelFor(model => model.DogOwnerId, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">


                            @Html.AutocompleteFor(model => model.DogOwnerForSearch, model => model.DogOwnerId, "GetOwner", "TypeAhead", false, new { htmlAttributes = new { placeholder = "Type the Owner Name" } })
                            @Html.HiddenFor(model => model.DogOwnerId)
                            @Html.ValidationMessageFor(model => model.DogOwnerId)
                        </div>
                    </div>
                </div>
                <div role="tabpanel" class="tab-pane" id="profile">
                    <div class="form-group">
                        @Html.LabelFor(model => model.DogOwner.Name, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DogOwner.Name)
                            @Html.ValidationMessageFor(model => model.DogOwner.Name)
                        </div>
                    </div>

                </div>
            </div>




        </div>

        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Add</button>
        </div>
}
                </div>
            </div>
        </div>
    </div>
</div>