DogMode.Admin/DogMode.Admin/Controllers/StatisticsController.cs
using DogMode.BusinessAccess.Extensions;
using DogMode.BusinessAccess.Repositories;
using DogMode.Models;
using Newtonsoft.Json;
using PagedList;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace DogMode.Admin.Controllers
{
    public class StatisticsController : BaseController<StatisticsRepository, Dog>
    {
        // GET: Statistics
        public async Task<ActionResult> Index()
        { 
            return View();
        }

        #region Grid Functions

        /// <summary>
        /// Ajax Async Search Grid.
        /// </summary>
        /// <param name="filter"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult SearchAync(FilterOptionModel filter)
        {
            filter.companyId = ClaimsPrincipal.Current.CenterId();
            var model = Repository.Search(filter);
            ViewBag.FilterModel = filter.Serialize();


            return View("Partials/StatisticsGrid", model.ToPagedList(filter.page == 0 ? 1 : filter.page, filter.Limit));
        }

        public ActionResult SearchFeeds(string filterdata, int? page, string columnName, string sortOrder)
        {
            var filter = JsonConvert.DeserializeObject<FilterOptionModel>(filterdata);
            var model = Repository.Search(filter);

            filter.page = page != null ? (int)page : 1;

            ViewBag.FilterModel = JsonConvert.SerializeObject(filter);
            ViewBag.Filter = filter;

            if (!string.IsNullOrEmpty(columnName) && !string.IsNullOrEmpty(sortOrder))
            {
                ViewBag.CurrentColumnSort = columnName;
                ViewBag.SortOrder = sortOrder;
                return View("Partials/StatisticsGrid", model.OrderBy(columnName, sortOrder).ToPagedList(page ?? 1, filter.Limit));
            }

            return View("Partials/StatisticsGrid", model.ToPagedList(page ?? 1, filter.Limit));
        }

        [HttpPost]
        public ActionResult Sort(string filter, string columnName, string sortOrder, string currentColumn, int? page)
        {
            var _filter = JsonConvert.DeserializeObject<FilterOptionModel>(filter);
            var model = Repository.Search(_filter);

            sortOrder = string.IsNullOrEmpty(sortOrder) ? "ASC" : sortOrder == "ASC" ? "DESC" : "ASC";

            if (currentColumn != null)
                sortOrder = columnName != currentColumn ? "ASC" : sortOrder;

            ViewBag.CurrentColumnSort = columnName;
            ViewBag.SortOrder = sortOrder;
            ViewBag.FilterModel = filter;

            return View("Partials/StatisticsGrid", model.OrderBy(columnName, sortOrder).ToPagedList(_filter.page == 0 ? 1 : _filter.page, _filter.Limit));
        }

        #endregion Grid Regions


        #region Summary

        public async Task<ActionResult> MostViewed()
        {
            var model = await Repository.GetMostViewedFeeds();

            return View("Partials/MostViewed", model);

        }

        public async Task<ActionResult> ViewsPerMonths()
        {
            return Json(await Repository.ViewsLastSixMonthsAsync(), JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> ViewsLastMonth()
        {
            return Json(await Repository.ViewsLasMonthAsync(), JsonRequestBehavior.AllowGet);
        }
        #endregion     Summary
    }
}

DogMode.Admin/DogMode.Admin/Views/Statistics/Partials/Filter.cshtml
@{
    Layout = null;
}
@model   FilterOptionModel
@using (Ajax.BeginForm("SearchAync", "Statistics", null, new AjaxOptions
{
    HttpMethod = "post",
    InsertionMode = InsertionMode.Replace,
    LoadingElementId = "loaderSection",
    UpdateTargetId = "tablecontainer",

}, new { id = "searchstatisticsform" }))
{
    
                           
 
<div class="row">
    <div class="col-sm-2">
        <div class="form-group">
            <label class="control-label" for="product_name">Titulo</label>
            
            @Html.EditorFor(m=> m.keywords)
        </div>
    </div>
    @*<div class="col-sm-3">
        <div class="form-group">
            <label class="control-label" for="price">Number of Views</label>
            
            @Html.EditorFor(m=> m.Limit)
        </div>
    </div>*@
    <div class="col-sm-2">
        <div class="form-group">
            <label class="control-label" for="quantity">Inicio</label>
          
            @Html.EditorFor(m=> m.time)

        </div>
    </div>
    <div class="col-sm-2">
        <div class="form-group">
            <label class="control-label" for="status">Estado</label>
             
            @Html.DropDownListFor(m=> m.FeedStatus ,CollectionExtensions.FeedStatuses,new { @class="form-control",onchange= "refreshGrid();"})
        </div>
    </div>
    <div class="col-sm-2">
        <div class="form-group">
            <label class="control-label" for="status">Categoria</label>

            @Html.DropDownListFor(m => m.CategoryId, ((IEnumerable<SelectListItem>) ViewBag.Categories), new { @class = "form-control", onchange="refreshGrid();" })
        </div>
    </div>
    <div class="col-sm-2">
        <div class="form-group">

            <button type="submit" id="loading-example-btn" class="btn btn-sm btn-success"><i class="fa fa-refresh"></i> </button>
        </div>

    </div>
</div>

}
 

DogMode.Admin/DogMode.Admin/Views/Statistics/Partials/MostViewed.cshtml
@{ 
    Layout = null;
}
@model IEnumerable<StatisticsViewModel>
<table class="table small m-t-sm">
    @foreach(var item in Model)
    {
        <tbody>
            <tr>
                <td>
                    <strong>@item.ViewCounts </strong>
                    @item.Title
                </td>
            </tr>
        </tbody>
    }
    @*<tbody>
        <tr>
            <td>
                <strong>142</strong> Projects

            </td>
            <td>
                <strong>22</strong> Messages
            </td>

        </tr>
        <tr>
            <td>
                <strong>61</strong> Comments
            </td>
            <td>
                <strong>54</strong> Articles
            </td>
        </tr>
        <tr>
            <td>
                <strong>154</strong> Companies
            </td>
            <td>
                <strong>32</strong> Clients
            </td>
        </tr>
    </tbody>
</table>*@

DogMode.Admin/DogMode.Admin/Views/Statistics/Partials/StatisticsGrid.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<StatisticsViewModel>

@{
    Layout = null;
    var filter = (string)ViewBag.FilterModel;
    var sortOrder = (string)ViewBag.SortOrder;
    var currentColumnOrder = (string)ViewBag.CurrentColumnSort;

    var options = new AjaxOptions() { HttpMethod = "POST", UpdateTargetId = "tablecontainer", LoadingElementId = "loaderSection" };
}

<table class="table table-striped">
    <tr>
        <th>
            @Ajax.ActionLink("ID", "Sort", new { filter = filter, columnName = "FeedId", sortOrder = sortOrder, currentColumn = currentColumnOrder }, options)
        </th>
        <th>
            @Ajax.ActionLink("Titulo", "Sort", new { filter = filter, columnName = "Title", sortOrder = sortOrder, currentColumn = currentColumnOrder }, options)
        </th>
        @*<th>
            @Ajax.ActionLink("Author", "Sort", new { filter = filter, columnName = "Author", sortOrder = sortOrder, currentColumn = currentColumnOrder }, options)
        </th>*@
        <th>

            @Ajax.ActionLink("Fecha Inicio", "Sort", new { filter = filter, columnName = "DateStart", sortOrder = sortOrder, currentColumn = currentColumnOrder }, options)
        </th>
        <th>

            @Ajax.ActionLink("Fecha Final", "Sort", new { filter = filter, columnName = "DateEnd", sortOrder = sortOrder, currentColumn = currentColumnOrder }, options)
        </th>
        <th>
            @Ajax.ActionLink("Categoria","Sort",new { filter= filter, columnName = "CategoryId", sortOrder = sortOrder, currentColumn = currentColumnOrder },options)
        </th>
        @*<th>
            @Ajax.ActionLink("Conteo Vistas", "Sort", new { filter = filter, columnName = "ViewCounts", sortOrder = sortOrder, currentColumn = currentColumnOrder }, options)
        </th>
        <th>
            @Ajax.ActionLink("Valoration Counts", "Sort", new { filter = filter, columnName = "ValorationsCount", sortOrder = sortOrder, currentColumn = currentColumnOrder }, options)
        </th>
        <th>
            @Ajax.ActionLink("Valorations", "Sort", new { filter = filter, columnName = "HasValorations", sortOrder = sortOrder, currentColumn = currentColumnOrder }, options)
        </th>*@
    </tr>


    <tbody>
       
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem=> item.FeedId)</td>
                <td>@Html.DisplayFor(modelItem=> item.Title)</td>
                @*<td>@Html.DisplayFor(modelItem => item.Author)</td>*@
                <td>@Html.DisplayFor(modelItem => item.DateStart)</td>
                <td>@Html.DisplayFor(modelItem => item.DateEnd)</td>
                <td>@Html.DisplayFor(modelItem => item.Category.Name)</td>
                @*<td>@Html.DisplayFor(modelItem => item.ViewCounts)</td>
                <td>@Html.DisplayFor(modelItem => item.ValorationsCount)</td>*@
                @*<td>
                    @if (item.HasValorations)
                    {
                        <p><span class="badge">@item.OptionCount1</span><small> @item.OptionLabel1 </small> </p>
                        <p><span class="badge">@item.OptionCount2</span><small> @item.OptionLabel2 </small> </p>
                        <p><span class="badge">@item.OptionCount3</span><small> @item.OptionLabel3 </small> </p>
                        <p><span class="badge">@item.OptionCount4</span><small> @item.OptionLabel4 </small> </p>
                        <p><span class="badge">@item.OptionCount5</span><small> @item.OptionLabel5 </small> </p>
                *@

                            @*<table class="table table-stripped small m-t-md">
                                <tbody>
                                    <tr>
                                        <td class="no-borders">
                                            <i class="fa fa-circle text-navy"></i>
                                        </td>
                                        <td class="no-borders">
                                            Example element 1
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <i class="fa fa-circle text-navy"></i>
                                        </td>
                                        <td>
                                            Example element 2
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <i class="fa fa-circle text-navy"></i>
                                        </td>
                                        <td>
                                            Example element 3
                                        </td>
                                    </tr>
                                </tbody>
                            </table>*@
                @*        
                     
                    }
                </td>*@
            </tr>
        }
    </tbody>
</table>

<div class="row">
    <div class="col-lg-12 text-right">
        <div class="pager-num">
            @Html.PagedListPager(Model, page => Url.Action("SearchFeeds", new { filterdata = filter, page, columnName = currentColumnOrder, sortOrder }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "tablecontainer", LoadingElementId = "loaderSection" }))
        </div>
        <div class="pager-text">Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount</div>
    </div>
</div>